name: educonnect
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get: ^4.6.6
  shared_preferences: ^2.2.2
  gap: ^3.0.1
  local_auth: ^2.1.8
  card_swiper: ^3.0.1
  dio: ^5.4.0
  http: ^1.2.0
  image_picker: ^1.0.7
  camera: ^0.11.0+2
  geolocator: ^13.0.1
  flutter_speed_dial: ^7.0.0
  flutter_slidable: ^3.0.1
  dropdown_button2: ^2.3.9
  html: ^0.15.4
  translator: ^1.0.0
  lottie: ^3.1.0
  google_maps_flutter: ^2.5.3
  permission_handler: ^11.3.0
  font_awesome_flutter: ^10.7.0
  flutter_rating_bar: ^4.0.1
  ably_flutter: ^1.2.34
  uuid: ^4.3.3
  firebase_auth: ^5.5.1
  flutter_svg: ^2.0.17
  feather_icons: 1.2.0
  flutter_localizations:
  
    sdk: flutter
  flutter_polyline_points: ^2.0.0
  latlong2: ^0.9.1
  flutter_animator: ^3.2.2
  flutter_swipe_button: ^2.1.1+1
  firebase_core: ^3.12.1
  flutter_card_swiper: ^7.0.2
  pie_chart: ^5.4.0
  cloud_firestore: ^5.6.5
  flutter_pdfview: ^1.4.0
  percent_indicator: ^4.2.5
  timeago: ^3.7.0
  firebase_storage: ^12.4.5
  file_picker: ^10.1.2
  path: ^1.9.0
  url_launcher: ^6.3.1
  table_calendar: ^3.1.3
  #  TARJMA 
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Mylogo.png"
  background_color: "#000000"
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/map.json
    - assets/json/map_sombre.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
        - asset: assets/fonts/Montserrat/Montserrat-BlackItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-BoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLightItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
        - asset: assets/fonts/Montserrat/Montserrat-LightItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat/Montserrat-MediumItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat/Montserrat-SemiBoldItalic.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Tajwal/Cairo/static/Cairo-Regular.ttf
    - family: Tajwal/Tajawal
      fonts:
        - asset: assets/fonts/Tajwal/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajwal/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajwal/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajwal/Tajawal-Light.ttf
        - asset: assets/fonts/Tajwal/Tajawal-Medium.ttf
    - family: Barlow
      fonts:
        - asset: assets/fonts/Barlow/Barlow-Regular.ttf
        - asset: assets/fonts/Barlow/Barlow-Bold.ttf
          weight: 700
        - asset: assets/fonts/Barlow/Barlow-Italic.ttf
          style: italic
        - asset: assets/fonts/Barlow/Barlow-Light.ttf
          weight: 300
        - asset: assets/fonts/Barlow/Barlow-Medium.ttf
          weight: 500
        - asset: assets/fonts/Barlow/Barlow-SemiBold.ttf
          weight: 600


flutter_intl:
  enabled: true
